import { LanguageCode, SourceInfo, TagType } from "paperback-extensions-common";
import { Mmrcms, SourceCategory, SourceTag } from "../..";

const REMANGAS_DOMAIN = "https://remangas.top";

export const RemangasInfo: SourceInfo = {
	version: "1.0.0",
	name: "Remangas",
	description: "Extension that pulls manga from remangas.top",
	author: "Ankah",
	authorWebsite: "https://github.com/adrienseon",
	icon: "icon.png",
	hentaiSource: false,
	websiteBaseURL: REMANGAS_DOMAIN,
	sourceTags: [
		{
			text: "Notifications",
			type: TagType.GREEN,
		},
		{
			text: "Portuguese",
			type: TagType.GREY,
		},
	],
};

export class Remangas extends Mmrcms {
	baseUrl: string = REMANGAS_DOMAIN;
	languageCode: LanguageCode = LanguageCode.PORTUGUESE;
	sourceTraversalPathName: string = "manga";
	sourceCategories: SourceCategory[] = [
		{ id: "1", name: "Ação" },
		{ id: "2", name: "Aventura" },
		{ id: "3", name: "Comédia" },
		{ id: "4", name: "Doujinshi" },
		{ id: "5", name: "Drama" },
		{ id: "6", name: "Ecchi" },
		{ id: "7", name: "Fantasia" },
		{ id: "8", name: "Gender Bender" },
		{ id: "9", name: "Harem" },
		{ id: "10", name: "Histórico" },
		{ id: "11", name: "Terror" },
		{ id: "12", name: "Josei" },
		{ id: "13", name: "Artes Marciais" },
		{ id: "14", name: "Adulto" },
		{ id: "15", name: "Mecha" },
		{ id: "16", name: "Mistério" },
		{ id: "17", name: "One Shot" },
		{ id: "18", name: "Psicológico" },
		{ id: "19", name: "Romance" },
		{ id: "20", name: "Vida escolar" },
		{ id: "21", name: "Sci-fi" },
		{ id: "22", name: "Seinen" },
		{ id: "23", name: "Shoujo" },
		{ id: "24", name: "Shoujo Ai" },
		{ id: "25", name: "Shounen" },
		{ id: "26", name: "Shounen Ai" },
		{ id: "27", name: "Slice of Life" },
		{ id: "28", name: "Esporte" },
		{ id: "29", name: "Sobrenatural" },
		{ id: "30", name: "Tragédia" },
		{ id: "31", name: "Yaoi" },
		{ id: "32", name: "Yuri" },
		{ id: "33", name: "Isekai" },
		{ id: "34", name: "Guerra" },
		{ id: "35", name: "Sobrevivência" },
		{ id: "36", name: "Romance?" },
	];
	sourceTags: SourceTag[] = [
		{ id: "seinen", name: "seinen" },
		{ id: "ecchi", name: "ecchi" },
		{ id: "harem", name: "harem" },
		{ id: "isekai", name: "isekai" },
		{ id: "guerra", name: "guerra" },
		{ id: "shounen", name: "shounen" },
		{ id: "18", name: "+18" },
		{ id: "adulto", name: "Adulto" },
		{ id: "fantasia", name: "Fantasia" },
		{ id: "romance", name: "Romance" },
		{ id: "vida-escolar", name: "Vida Escolar" },
		{ id: "acao", name: "Ação" },
		{ id: "misterio", name: "mistério" },
		{ id: "terror", name: "Terror" },
		{ id: "detetive", name: "Detetive" },
		{ id: "misterios", name: "Mistérios" },
		{ id: "incesto", name: "Incesto" },
		{ id: "comedia-romantica", name: "Comédia Romantica" },
		{ id: "alquimia", name: "Alquimia" },
		{ id: "manhua", name: "Manhua" },
		{ id: "colorido", name: "Colorido" },
		{ id: "antologia", name: "Antologia" },
		{ id: "dragoes", name: "Dragões" },
		{ id: "briga-de-rua", name: "Briga de Rua" },
		{ id: "anti-heroi", name: "Anti Herói" },
		{ id: "zoera", name: "Zoera" },
		{ id: "protagonista-overpower", name: "Protagonista Overpower" },
		{ id: "psicologico", name: "Psicológico" },
		{ id: "protagonista-badass", name: "Protagonista Badass" },
		{ id: "battleroyale", name: "Battleroyale" },
		{ id: "apocalispe-zumbi", name: "Apocalispe Zumbi" },
		{ id: "mc-nao-virjao", name: "Mc Não Virjão" },
		{ id: "escola-de-magia", name: "Escola de Magia" },
		{ id: "tensei", name: "Tensei" },
		{ id: "shota-badass", name: "Shota Badass" },
		{ id: "isekai-vai-e-volta", name: "Isekai Vai e Volta" },
		{ id: "gore", name: "gore" },
		{ id: "garota-monstro", name: "Garota Monstro" },
		{ id: "maid", name: "Maid" },
		{ id: "gal", name: "Gal" },
		{ id: "mordomo", name: "Mordomo" },
	];
}
