import { LanguageCode, SourceInfo, TagType } from "paperback-extensions-common";
import { Mmrcms, SourceCategory, SourceTag, DateFormat } from "..";

export const MangaHantaInfo: SourceInfo = {
    version: "1.0.0",
    name: "MangaHanta",
    description: "Extension that pulls manga from mangahanta.com",
    author: "Ankah",
    authorWebsite: "https://github.com/adrienseon",
    icon: "icon.png",
    hentaiSource: false,
    websiteBaseURL: "http://mangahanta.com",
    sourceTags: [
        {
            text: "Notifications",
            type: TagType.GREEN,
        },
        {
            text: "Turkish",
            type: TagType.GREY,
        },
    ],
};

export class MangaHanta extends Mmrcms {
    name: string = MangaHantaInfo.name;
    baseUrl: string = MangaHantaInfo.websiteBaseURL;
    languageCode: LanguageCode = LanguageCode.TURKISH;
    dateFormat: DateFormat = {
        format: "DD/MM/YYYY",
        todayTranslation: "bugün",
        yesterdayTranslation: "dün",
    };
    sourceCategories: SourceCategory[] = [
        { id: "1", name: "Aksiyon" },
        { id: "2", name: "Macera" },
        { id: "3", name: "Komedi" },
        { id: "4", name: "Doujinshi" },
        { id: "5", name: "Drama" },
        { id: "6", name: "Ecchi" },
        { id: "7", name: "Fantezi" },
        { id: "8", name: "Gender Bender" },
        { id: "9", name: "Harem" },
        { id: "10", name: "Tarihi" },
        { id: "11", name: "Korku" },
        { id: "12", name: "Josei" },
        { id: "13", name: "Dövüş Sanatları" },
        { id: "14", name: "Yetişkin" },
        { id: "15", name: "Mecha" },
        { id: "16", name: "Gizem" },
        { id: "17", name: "One Shot" },
        { id: "18", name: "Psikolojik" },
        { id: "19", name: "Romantizm" },
        { id: "20", name: "Okul Hayatı" },
        { id: "21", name: "Bilim-Kurgu" },
        { id: "22", name: "Seinen" },
        { id: "23", name: "Shoujo" },
        { id: "24", name: "Shoujo Ai" },
        { id: "25", name: "Shounen" },
        { id: "26", name: "Shounen Ai" },
        { id: "27", name: "Hayattan Bir Parça" },
        { id: "28", name: "Spor" },
        { id: "29", name: "Doğaüstü" },
        { id: "30", name: "Trajedi" },
        { id: "31", name: "Yaoi" },
        { id: "32", name: "Yuri" },
        { id: "33", name: "Vampir" },
        { id: "34", name: "Webtoon" },
    ];
    sourceTags: SourceTag[] = [
        { id: "tag", name: "-ヒトガタナ-" },
        { id: "amber", name: "Amber" },
        { id: "amber-manga", name: "Amber manga" },
        { id: "amber-oku", name: "Amber oku" },
        { id: "amber-turkce-oku", name: "Amber Türkçe Oku" },
        { id: "amber-yuno", name: "Amber Yuno" },
        { id: "back-stage", name: "Back Stage" },
        { id: "ballroom-e-youkoso", name: "Ballroom e Youkoso" },
        { id: "beauty-game", name: "Beauty Game" },
        { id: "beauty-game-oku", name: "Beauty Game Oku" },
        { id: "boku-wa-mari-no-naka", name: "Boku Wa Mari No Naka" },
        { id: "god-eater-kyuuseishu-no-kikan", name: "God Eater - Kyuuseishu no Kikan" },
        { id: "god-eater-the-spiral-fate", name: "God Eater - The Spiral Fate" },
        { id: "happiness", name: "Happiness" },
        { id: "happiness-manga-oku", name: "happiness manga oku" },
        { id: "happiness-turkce-oku", name: "happiness türkçe oku" },
        { id: "hitogatana", name: "Hitogatana" },
        { id: "im-in-mari-im-inside-mari", name: "ぼくは麻理のなか I\u0027m in Mari I\u0027m Inside Mari" },
        { id: "itsuwaribito-utsuho", name: "Itsuwaribito Utsuho" },
        { id: "kaguya-sama-wa-kokurasetai", name: "Kaguya-sama wa Kokurasetai" },
        { id: "les-memoires-de-vanitas", name: "Les Mémoires de Vanitas" },
        { id: "mahouka-koukou-no-rettousei-tsuioku-hen", name: "Mahouka Koukou no Rettousei - Tsuioku Hen" },
        { id: "manga-oku", name: "manga oku" },
        { id: "maou-na-ore-to-fushihime-no-yubiwa", name: "Maou na Ore to Fushihime no Yubiwa" },
        { id: "may-i-shake-your-hand", name: "May I shake your hand" },
        { id: "may-i-shake-your-hand-oku", name: "may I shake your hand oku" },
        { id: "may-i-shake-your-hand-turkce-oku", name: "May I Shake Your Hand türkçe oku" },
        { id: "memoir-of-vanitas", name: "Memoir of Vanitas" },
        { id: "mutluluk", name: "Mutluluk" },
        { id: "nanatsu-no-taizai", name: "Nanatsu No Taizai" },
        { id: "nanatsu-no-taizai-turkce-oku", name: "Nanatsu no taizai Türkçe oku" },
        { id: "oshimi-shuzo", name: "OSHIMI Shuzo" },
        { id: "sousei-manga-oku", name: "sousei manga oku" },
        { id: "sousei-no-onmyouji", name: "Sousei no Onmyouji" },
        { id: "sousei-no-onmyouji-manga-oku", name: "Sousei no onmyouji manga oku" },
        { id: "sousei-no-onmyouji-turkce-oku", name: "sousei no onmyouji türkçe oku" },
        { id: "the-case-study-of-vanitas", name: "The Case Study of Vanitas" },
        { id: "the-seven-deadly-sins", name: "The Seven Deadly Sins" },
        { id: "vanitas-no-carte", name: "Vanitas no Carte" },
        { id: "vanitas-no-shuki", name: "Vanitas no Shuki" },
        { id: "yedi-olumcul-gunah", name: "Yedi Ölümcül Günah" },
    ];
}
