import { LanguageCode, SourceInfo, TagType } from "paperback-extensions-common";
import { Mmrcms, SourceCategory } from "../..";

const READCOMICSONLINERU_DOMAIN = "https://readcomicsonline.ru";

export const ReadComicsOnlineRuInfo: SourceInfo = {
	version: "1.0.0",
	name: "ReadComicsOnline.ru",
	description: "Extension that pulls manga from readcomicsonline.ru",
	author: "Ankah",
	authorWebsite: "https://github.com/adrienseon",
	icon: "icon.png",
	hentaiSource: false,
	websiteBaseURL: READCOMICSONLINERU_DOMAIN,
	sourceTags: [
		{
			text: "Notifications",
			type: TagType.GREEN,
		},
	],
};

export class ReadComicsOnlineRu extends Mmrcms {
	baseUrl: string = READCOMICSONLINERU_DOMAIN;
	languageCode: LanguageCode = LanguageCode.ENGLISH;
	sourceTraversalPathName: string = "comic";
	sourceCategories: SourceCategory[] = [
		{ id: "1", name: "One Shots \u0026 TPBs" },
		{ id: "2", name: "DC Comics" },
		{ id: "3", name: "Marvel Comics" },
		{ id: "4", name: "Boom Studios" },
		{ id: "5", name: "Dynamite" },
		{ id: "6", name: "Rebellion" },
		{ id: "7", name: "Dark Horse" },
		{ id: "8", name: "IDW" },
		{ id: "9", name: "Archie" },
		{ id: "10", name: "Graphic India" },
		{ id: "11", name: "Darby Pop" },
		{ id: "12", name: "Oni Press" },
		{ id: "13", name: "Icon Comics" },
		{ id: "14", name: "United Plankton" },
		{ id: "15", name: "Udon" },
		{ id: "16", name: "Image Comics" },
		{ id: "17", name: "Valiant" },
		{ id: "18", name: "Vertigo" },
		{ id: "19", name: "Devils Due" },
		{ id: "20", name: "Aftershock Comics" },
		{ id: "21", name: "Antartic Press" },
		{ id: "22", name: "Action Lab" },
		{ id: "23", name: "American Mythology" },
		{ id: "24", name: "Zenescope" },
		{ id: "25", name: "Top Cow" },
		{ id: "26", name: "Hermes Press" },
		{ id: "27", name: "451" },
		{ id: "28", name: "Black Mask" },
		{ id: "29", name: "Chapterhouse Comics" },
		{ id: "30", name: "Red 5" },
		{ id: "31", name: "Heavy Metal" },
		{ id: "32", name: "Bongo" },
		{ id: "33", name: "Top Shelf" },
		{ id: "34", name: "Bubble" },
		{ id: "35", name: "Boundless" },
		{ id: "36", name: "Avatar Press" },
		{ id: "37", name: "Space Goat Productions" },
		{ id: "38", name: "BroadSword Comics" },
		{ id: "39", name: "AAM-Markosia" },
		{ id: "40", name: "Fantagraphics" },
		{ id: "41", name: "Aspen" },
		{ id: "42", name: "American Gothic Press" },
		{ id: "43", name: "Vault" },
		{ id: "44", name: "215 Ink" },
		{ id: "45", name: "Abstract Studio" },
		{ id: "46", name: "Albatross" },
		{ id: "47", name: "ARH Comix" },
		{ id: "48", name: "Legendary Comics" },
		{ id: "49", name: "Monkeybrain" },
		{ id: "50", name: "Joe Books" },
		{ id: "51", name: "MAD" },
		{ id: "52", name: "Comics Experience" },
		{ id: "53", name: "Alterna Comics" },
		{ id: "54", name: "Lion Forge" },
		{ id: "55", name: "Benitez" },
		{ id: "56", name: "Storm King" },
		{ id: "57", name: "Sucker" },
		{ id: "58", name: "Amryl Entertainment" },
		{ id: "59", name: "Ahoy Comics" },
		{ id: "60", name: "Mad Cave" },
		{ id: "61", name: "Coffin Comics" },
		{ id: "62", name: "Magnetic Press" },
		{ id: "63", name: "Ablaze" },
		{ id: "64", name: "Europe Comics" },
		{ id: "65", name: "Humanoids" },
		{ id: "66", name: "TKO" },
		{ id: "67", name: "Soleil" },
		{ id: "68", name: "SAF Comics" },
		{ id: "69", name: "Scholastic" },
		{ id: "70", name: "Upshot" },
		{ id: "71", name: "Stranger Comics" },
		{ id: "72", name: "Inverse" },
		{ id: "73", name: "Virus" },
	];
}
